version: 1
jobs:
  deploy:
    steps:
    - npm install
    - npm install -g zcatalyst-cli@beta
    # - cd scripts
    # - npm install
    - env
    - catalyst deploy
        
stages:
  - name: build
    jobs:
        - deploy