version: 1
jobs:
  deploy:
    steps:
    - npm install
     - npm install -g zcatalyst-cli@beta
    - npm run build
    - cd server
    - npm install
    - cd ..
    - cd scripts
    - npm install
    - cd ..
    - env
    - catalyst deploy
        
stages:
  - name: build
    jobs:
        - deploy